const carManufacturers: string[] = [
	"Toyota",
	"Honda",
	"Ford",
	"Chevrolet",
	"Volkswagen",
	"Nissan",
	"Hyundai",
	"Kia",
	"BMW",
	"Mercedes-Benz",
	"Audi",
	"Lexus",
	"Mazda",
	"Subaru",
	"Tesla",
	"Volvo",
	"Jeep",
	"Chrysler",
	"Mitsubishi",
	"Land Rover",
	"Porsche",
	"Ferrari",
	"Lamborghini",
	"Bugatti",
	"Alfa Romeo",
	"Jaguar",
	"Buick",
	"Cadillac",
	"Lincoln",
	"Acura",
	"Infiniti",
	"GMC",
	"Mini",
	"Maserati",
	"Bentley",
	"McLaren",
	"Rolls-Royce",
	"Vauxhall",
	"Suzuki",
	"Renault",
	"Peugeot",
	"Citroën",
	"Fiat",
	"Dodge",
	"Koenigsegg",
	"Lotus",
	"Aston Martin",
	"Genesis",
	"Pagani",
	"Lancia",
	"Smart",
	"Saab",
	"Dacia",
];

carManufacturers.sort();

export { carManufacturers };

export const footerLinks = [
	{
		title: "About",
		links: [
			{ title: "Overview", url: "/" },
			{ title: "Featured", url: "/" },
			{ title: "Partnership", url: "/" },
			{ title: "Bussiness Relation", url: "/" },
		],
	},
	{
		title: "Company",
		links: [
			{ title: "Events", url: "/" },
			{ title: "Blog", url: "/" },
			{ title: "Newsletter", url: "/" },
			{ title: "Help Center", url: "/" },
		],
	},
	{
		title: "Socials",
		links: [
			{ title: "Discord", url: "/" },
			{ title: "Instagram", url: "/" },
			{ title: "Twitter", url: "/" },
			{ title: "Facebook", url: "/" },
		],
	},
	{
		title: "Legal",
		links: [
			{ title: "Terms", url: "/" },
			{ title: "Privacy", url: "/" },
			{ title: "License", url: "/" },
			{ title: "Settings", url: "/" },
		],
	},
];
